### ISSUE TITLE
Header breaking the responsive layout

### ISSUE THREAD

**Issue by tonifisler** [antistatique/sawi-styleguide#1]
![screen shot 2016-07-26 at 09 00 56](https://cloud.githubusercontent.com/assets/1708450/17128794/8bf4b7e6-530f-11e6-82ab-4832a4f0a040.png)

Appears to be caused by:

``` css
h3.header-title {
    min-width: 7em;
}
```

Noticed on Chrome, using the device inspector.
